make:
	cc -o bezier1 bezier1.c -lGL -lGLU -lglut /usr/lib/x86_64-linux-gnu/libdrm.a -lm -g
	./bezier1

compile:
	cc -o bezier1 bezier1.c -lGL -lGLU -lglut /usr/lib/x86_64-linux-gnu/libdrm.a -lm -g
	
run:
	./bezier1

debug:
	gdb ./bezier1