make:
	cc -o monkeyDance monkeyDance.c -lGL -lGLU -lglut /usr/lib/x86_64-linux-gnu/libdrm.a -lm -g
	./monkeyDance


compile:
	cc -o monkeyDance monkeyDance.c -lGL -lGLU -lglut /usr/lib/x86_64-linux-gnu/libdrm.a -lm -g
	
run:
	./monkeyDance

steeeeam:
	sl
